/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-06-08 03:16:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>join</title>\r\n");
      out.write("<style>\r\n");
      out.write("div.button{\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\twidth : 50%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction checkForm(){\r\n");
      out.write("\t\tif(!document.join.id.value){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!document.join.password.value){\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(document.join.password.value != document.join.passwordconfirm.value){\r\n");
      out.write("\t\t\talert(\"비밀번호를 동일하게 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\talert(\"회원가입이 완료되었습니다. 로그인 해주세요.\");\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class='preloader'><div class='loaded'>&nbsp;</div></div>\r\n");
      out.write("        <div class=\"culmn\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("        \t\t <!-- Counter Section --> \r\n");
      out.write("            <section id=\"counter\" class=\"counter\">\r\n");
      out.write("                <div class=\"video_overlay\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">  \r\n");
      out.write("                            <div class=\"col-sm-12\">               \r\n");
      out.write("                                <div class=\"main_counter_area text-center\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <div class=\"head_title text-center\" style=\"color:white; margin-top:80px;\">\r\n");
      out.write("                                 \t   <h2 style=\"font-size:50pt;\">JOIN</h2>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- End off container --> \r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("<form name=\"join\" action=\"JoinMemberAction.do\" method=\"post\" onsubmit = \"return checkForm();\" style =\"margin:0 auto; width:500px;\">\r\n");
      out.write("  <fieldset>\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("      <label for=\"id\" class=\"col-sm-2 col-form-label\" style=\"position:relative; font-size:15pt; left:40px; margin-top:10px;\">ID</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"id\" placeholder=\"ID\" style=\"width:300px; position: relative; left:95px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("      <label for=\"name\" class=\"col-sm-2 col-form-label\" style=\"position:relative; font-size:15pt; left:40px; margin-top:10px;\">Name</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"name\" placeholder=\"Name\" style=\"width:300px; position: relative; left:95px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("      <label for=\"nickname\" class=\"col-sm-2 col-form-label\" style=\"position:relative; font-size:15pt; left:40px; margin-top:10px;\">Nickname</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"nickname\" placeholder=\"Nickname\" style=\"width:300px; position: relative; left:95px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("      <label for=\"exampleInputEmail1\" class=\"col-sm-2 com-form-label\" style=\"position:relative; font-size:15pt; left:40px;\">Email Address</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"email1\" aria-describedby=\"emailHelp\" placeholder=\"Email\" maxlength=\"20\" style=\"width:150px; float:left; position: relative; left:95px;\"><p style=\"float:left; margin-top:15px; position: relative; left:95px;\">@</p>\r\n");
      out.write("      <select name=\"email2\" style=\"width:150px; margin-top:15px; position: relative; left:95px;\">\r\n");
      out.write("\t\t\t\t\t<option>naver.com</option>\r\n");
      out.write("\t\t\t\t\t<option>daum.net</option>\r\n");
      out.write("\t\t\t\t\t<option>gmail.com</option>\r\n");
      out.write("\t\t\t\t\t<option>nate.com</option>\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("      <label for=\"exampleInputPassword1\" class=\"col-sm-2 col-form-label\" style=\"position:relative; font-size:15pt; left:40px; margin-top:10px;\">Password</label>\r\n");
      out.write("      <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" placeholder=\"Password\" style=\"width:300px; position: relative; left:95px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("\t\t\t<label for=\"exampleInputPassword1\" class=\"col-sm-2 col-form-label\" style=\"position:relative; font-size:15pt; left:40px;\">Password Confirm</label>\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"form-control\" name =\"passwordconfirm\" id=\"passwordconfirm\" placeholder=\"Password Confirm\" style=\"width:300px; position: relative; left:95px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("      <label for=\"phonenumber\" class=\"col-sm-2 col-form-label\" style=\"position:relative; font-size:15pt; left:40px;\">Phone Number</label>\r\n");
      out.write("      <div style=\"position: relative; left:95px;\">\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" name=\"phone1\" value=\"010\" maxlength=\"3\" style=\"width:90px; float:left;\">\r\n");
      out.write("        <p style=\"float:left;\"> - </p><input type=\"text\" class=\"form-control\" name=\"phone2\" maxlength=\"4\" style=\"width:90px; float:left;\">\r\n");
      out.write("        <p style=\"float:left;\"> - </p><input type=\"text\" class=\"form-control\" name=\"phone3\" maxlength=\"4\" style=\"width:90px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    <div class=\"form-group row\">\r\n");
      out.write("      <label for=\"address\" class=\"col-sm-2 col-form-label\" style=\"position:relative; font-size:15pt; left:40px; margin-top:10px;\">Address</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"address\" placeholder=\"Address\" style=\"width:500px; position: relative; left:55px\">\r\n");
      out.write("    </div>\r\n");
      out.write(" </fieldset>\r\n");
      out.write("    <fieldset class=\"form-group row\">\r\n");
      out.write("      <label class=\"col-sm-2 col-form-label\" style=\"position:relative; font-size:15pt; left:40px; margin-top:10px;\">Gender</label>\r\n");
      out.write("      <div style=\"width:500px; position: relative; left:95px; margin-top:10px;\">\r\n");
      out.write("      <div class=\"form-check\" style=\"float:left;\">\r\n");
      out.write("        <label class=\"form-check-label\">\r\n");
      out.write("          <input type=\"radio\" class=\"form-check-input\" name=\"gender\" id=\"optionsRadios1\" value=\"female\" checked=\"\">Female\r\n");
      out.write("        </label>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-check\">\r\n");
      out.write("      <label class=\"form-check-label\">\r\n");
      out.write("          <input type=\"radio\" class=\"form-check-input\" name=\"gender\" id=\"optionsRadios2\" value=\"male\"> Male\r\n");
      out.write("        </label>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </fieldset>\r\n");
      out.write("    <div style=\"position: relative; left:95px;\">\r\n");
      out.write("\t<input type=\"submit\" class=\"btn btn-default\" style=\"color:white; background-color:#68a5f3;\" value=\"Submit\">\r\n");
      out.write("\t<input type=\"reset\" class=\"btn btn-default\" style=\"color:white; background-color:#68a5f3;\" value=\"Cancel\" onclick=\"location='index.jsp'\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write(" <script src=\"resources/assets/js/vendor/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resources/assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/jquery.mixitup.min.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/jquery.masonry.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!--slick slide js -->\r\n");
      out.write("        <script src=\"resources/assets/css/slick/slick.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/css/slick/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resources/assets/js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
