/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-06-08 14:14:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class Write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1590720193505L));
    _jspx_dependants.put("jar:file:/C:/Users/LG/eclipse-workspace/aj20/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Europe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function cancel(){\r\n");
      out.write("\twindow.history.back(); \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
 request.setCharacterEncoding("utf-8"); 
      out.write("\r\n");
      out.write("<body>\r\n");

String userID = (String)session.getAttribute("userID");
String userPW = (String)session.getAttribute("userPW"); 

      out.write("\r\n");
      out.write("<div class='preloader'><div class='loaded'>&nbsp;</div></div>\r\n");
      out.write("        <div class=\"culmn\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("        \t\t <!-- Counter Section --> \r\n");
      out.write("            <section id=\"counter\" class=\"counter\">\r\n");
      out.write("                <div class=\"video_overlay\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row\">  \r\n");
      out.write("                            <div class=\"col-sm-12\">               \r\n");
      out.write("                                <div class=\"main_counter_area text-center\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t <div class=\"head_title text-center\" style=\"color:white; margin-top:80px;\">\r\n");
      out.write("                                 \t   <h2 style=\"font-size:50pt;\">WRITE</h2>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div><!-- End off container --> \r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("<form action=\"AddAction.do\" method=\"post\" style =\"margin:0 auto; width:1000px;\">\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write("      <label for=\"Category\" class=\"col-sm-2 com-form-label\" style=\"position: relative; font-size:15pt; left:130px;\">나라/주제</label>\r\n");
      out.write("      <div style=\"position: relative; left:95px;\">\r\n");
      out.write("      <select name=\"country\" style=\"background-color:#fbfbfb; width:150px; float:left;\">\r\n");
      out.write("\t\t\t\t\t<option>Korea</option>\r\n");
      out.write("\t\t\t\t\t<option>England</option>\r\n");
      out.write("\t\t\t\t\t<option>France</option>\r\n");
      out.write("\t\t\t\t\t<option>Swiss</option>\r\n");
      out.write("\t\t\t\t\t<option>Germany</option>\r\n");
      out.write("\t\t\t\t\t<option>Hungary</option>\r\n");
      out.write("\t\t\t\t\t<option>Czech</option>\r\n");
      out.write("\t\t\t\t\t<option>Italy</option>\r\n");
      out.write("\t  </select>\r\n");
      out.write("\t  <select name=\"cate1\" style=\"background-color:#fbfbfb; width:150px; float:left;\">\r\n");
      out.write("\t\t\t\t\t<option>Information</option>\r\n");
      out.write("\t\t\t\t\t<option>Market</option>\r\n");
      out.write("\t\t\t\t\t<option>Together</option>\r\n");
      out.write("\t  </select>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"form-group row\">\r\n");
      out.write("      <label for=\"title\" class=\"col-sm-2 col-form-label\" style=\"position: relative; font-size:15pt; left:130px; margin-top:10px;\">제목</label>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"title\" placeholder=\"제목을 입력해주세요.\" style=\"background-color:#fbfbfb; width:700px; position: relative; left:95px;\">\r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"form-group\">\r\n");
      out.write("      <label for=\"inputfile\" style=\"position: relative; font-size:15pt; left:130px;\">파일첨부</label>\r\n");
      out.write("      <div class=\"col-sm-10\" style=\"position: relative; left:70px; float:right;\">\r\n");
      out.write("      <input type=\"file\" class=\"form-control-file\" name=\"inputfile\" aria-describedby=\"fileHelp\">\r\n");
      out.write("      <small id=\"fileHelp\" class=\"form-text text-muted\" style=\"color:red\">※글과 관련된 사진만 첨부하여 주십시오.※</small>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-group\">\r\n");
      out.write("      <label for=\"detail\" style=\"position: relative; font-size:15pt; left:130px; margin-top:10px;\">내용</label>\r\n");
      out.write("      <br>\r\n");
      out.write("      <textarea class=\"form-control\" name=\"detail\" placeholder=\"내용을 입력해주세요.\" style=\"background-color:#fbfbfb; height:600px; width:830px; position: relative; left:130px;\"></textarea>\r\n");
      out.write("    </div>\r\n");
      out.write("    <input type=\"hidden\" name=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.getNickname()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("\t<div style=\"position: relative; left:350px;\">\r\n");
      out.write("\t<input type=\"submit\" class=\"btn btn-default\" style=\"color:white; background-color:#68a5f3;\" value=\"작성\">\r\n");
      out.write("\t<input type=\"button\" class=\"btn btn-default\" style=\"color:white; background-color:#68a5f3;\" value=\"취소\" onclick = \"cancel()\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write(" <script src=\"resources/assets/js/vendor/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/vendor/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resources/assets/js/jquery.magnific-popup.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/jquery.mixitup.min.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/jquery.masonry.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <!--slick slide js -->\r\n");
      out.write("        <script src=\"resources/assets/css/slick/slick.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/css/slick/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"resources/assets/js/plugins.js\"></script>\r\n");
      out.write("        <script src=\"resources/assets/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
